import {
	Link2,
	Instagram,
	Youtube,
	Twitter,
	Facebook,
	Linkedin,
	Github,
	Music,
	Mail,
	Phone,
	MapPin,
	ShoppingBag,
	Camera,
	Globe,
	Heart,
	Star,
	Coffee,
	BookOpen,
	Video,
	Mic,
	MessageCircle,
} from 'lucide-react';

export const LINK_ICON_OPTIONS = [
	{ id: 'link', label: 'Enlace', Icon: Link2 },
	{ id: 'instagram', label: 'Instagram', Icon: Instagram },
	{ id: 'youtube', label: 'YouTube', Icon: Youtube },
	{ id: 'twitter', label: 'X', Icon: Twitter },
	{ id: 'facebook', label: 'Facebook', Icon: Facebook },
	{ id: 'linkedin', label: 'LinkedIn', Icon: Linkedin },
	{ id: 'github', label: 'GitHub', Icon: Github },
	{ id: 'tiktok', label: 'TikTok', Icon: Video },
	{ id: 'whatsapp', label: 'WhatsApp', Icon: MessageCircle },
	{ id: 'music', label: 'Música', Icon: Music },
	{ id: 'podcast', label: 'Podcast', Icon: Mic },
	{ id: 'mail', label: 'Email', Icon: Mail },
	{ id: 'phone', label: 'Teléfono', Icon: Phone },
	{ id: 'map-pin', label: 'Ubicación', Icon: MapPin },
	{ id: 'shopping-bag', label: 'Tienda', Icon: ShoppingBag },
	{ id: 'camera', label: 'Fotos', Icon: Camera },
	{ id: 'globe', label: 'Web', Icon: Globe },
	{ id: 'heart', label: 'Favorito', Icon: Heart },
	{ id: 'star', label: 'Destacado', Icon: Star },
	{ id: 'coffee', label: 'Café', Icon: Coffee },
	{ id: 'book', label: 'Blog', Icon: BookOpen },
	{ id: 'video', label: 'Video', Icon: Video },
];

export const getLinkIconOption = (iconId) =>
	LINK_ICON_OPTIONS.find((option) => option.id === iconId) || LINK_ICON_OPTIONS[0];
